# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  
  config.vm.define "ubuntu" do |ubuntu|
    ubuntu.vm.box = "ubuntu/focal64"
  end
  
  config.vm.define "fedora" do |fedora|
    fedora.vm.box = "generic/fedora35"
  end

end
